# Generated by Django 5.2.12 on 2026-03-19 22:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('graph_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'graphs',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_models.graph')),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('edge_id', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='django_models.graph')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='django_models.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='django_models.node')),
            ],
            options={
                'db_table': 'edges',
            },
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('graph', 'node_id'), name='nodes_graph_nodeid_uq'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'from_node'], name='idx_edges_graph_from'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'id'], name='idx_edges_graph_id'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('graph', 'edge_id'), name='edges_graph_edgeid_uq'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='edge_cost_gte_zero'),
        ),
    ]
